algoritmo "Comparacao Com Operadores Relacionais"
var
   A, B, C: Inteiro
   
inicio
      A <- 2
      B <- 3
      C <- 5
      Escreval ("Maior que ", A>B)
      Escreval ("Igual a ", A=B)
      Escreval ("Diferente de ", A<>C)
      Escreval ("Maior ou igual a ", A>=B)
      Escreval (A<7)
      Escreval (B<=7)
      Escreval (C= A+B)
      Escreval (C>=B^A)
      Escreval (1=C%2) //  restante da divisao
fimalgoritmo
