algoritmo "Testes de conhecimento"
var
   Nome, Mes: caractere
   Dia, Ano: Real
inicio
      Escreva("Qual o nome da crianca: ")
      Leia(Nome)
      Escreva("Qual o dia que ", Nome, " nasceu: ")
      Leia(Dia)
      Escreva("Em qual mes que ", Nome, " nasceu: ")
      Leia(Mes)
      Escreva("Em qual ano que ", Nome, " nasceu: ")
      Leia(Ano)
      Escreva("O(a)", Nome, " nasceu em ", Dia, Mes, Ano)
      
fimalgoritmo
